### ISSUE TITLE
Make noarch: python?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/antlr-python-runtime-feedstock#29]
Now that we no longer support python2, we can make this `noarch: python`.

This would then probably collapse the need for https://github.com/conda-forge/antlr4-python3-runtime-feedstock/issues/1

**Comment by BastianZim** [comment]
I'll create the PRs.

**Comment by BastianZim** [comment]
It has a `scripts` tag, so no noarch but I'll still add the other package.

**Comment by bollwyvl** [comment]
> It has a scripts tag

ha, right, how soon i forget

**Comment by bollwyvl** [comment]
We _could_ patch... but it might get nasty.

**Comment by BastianZim** [comment]
I was thinking the same but our source is PyPI. Is it possible to patch that too? Wasn't sure if that's restricted to GitHub as a source.

Edit: I've tried patching it but it's not working. If you have any ideas, feel free to push to my branch directly.

**Comment by bollwyvl** [comment]
As of #31 is now noarch.
