### ISSUE TITLE
Build version 4.8 for osx-arm64

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/antlr-python-runtime-feedstock#33]
https://github.com/conda-forge/hydra-core-feedstock is only compatible with version 4.8 of antlr - it would be great if antlr 4.8 could be built for osx-arm64 so the hydra-core (and in turn detectron2) can be used on osx-arm64.

**Comment by bollwyvl** [comment]
the lighter-weight path (e.g. to support future pythons, etc)  be to:
- make a `4.8` branch
- make that branch  `noarch: python` (since we no longer care about the py27 target)

i'll see what i can do, have limited connectivity.

**Comment by bollwyvl** [comment]
#35 is in, making a `noarch` 4.8: please have a look in ~2 hours, and re-open if there are further issues.
